// <auto-generated />
using System;
using Infra.Autenticacao;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infra.Migrations
{
    [DbContext(typeof(AutenticacaoContext))]
    [Migration("20240321235545_AdicionarRoles")]
    partial class AdicionarRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Autenticacao.AcessoUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("matricula");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senha");

                    b.HasKey("Id");

                    b.ToTable("acesso_usuario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("305af885-4794-4011-9e42-db3d23c7d8dd"),
                            Email = "jose.silva@gmail.com",
                            Matricula = "2200101",
                            Nome = "José Silva",
                            Role = 20,
                            Senha = "B5D3A85785B854548A440F1EA52F19EF920AB9ED29136B977861B5E36983DEA2C92F29D5939A427AAAEDBC67C3B48A6CD9E1D45483D3796E0A60F113240BB49C"
                        },
                        new
                        {
                            Id = new Guid("cc9eb831-4bc6-4f87-9342-2fcce1f6c29c"),
                            Email = "renata.barros@gmail.com",
                            Matricula = "2300102",
                            Nome = "Renata Barros",
                            Role = 20,
                            Senha = "B5D3A85785B854548A440F1EA52F19EF920AB9ED29136B977861B5E36983DEA2C92F29D5939A427AAAEDBC67C3B48A6CD9E1D45483D3796E0A60F113240BB49C"
                        },
                        new
                        {
                            Id = new Guid("65f3621e-f99c-475e-9430-00c11d91ec50"),
                            Email = "felipe.okagawa@gmail.com",
                            Matricula = "2400103",
                            Nome = "Felipe Okagawa",
                            Role = 20,
                            Senha = "B5D3A85785B854548A440F1EA52F19EF920AB9ED29136B977861B5E36983DEA2C92F29D5939A427AAAEDBC67C3B48A6CD9E1D45483D3796E0A60F113240BB49C"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
