// <auto-generated />
using System;
using Infra.Autenticacao;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infra.Migrations
{
    [DbContext(typeof(AutenticacaoContext))]
    [Migration("20240322214323_AddUserLuiz")]
    partial class AddUserLuiz
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Autenticacao.AcessoUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("matricula");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senha");

                    b.HasKey("Id");

                    b.ToTable("acesso_usuario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("52a120db-b0f9-43b9-aa04-88c0ee0e03c0"),
                            Email = "jose.silva@gmail.com",
                            Matricula = "2200101",
                            Nome = "José Silva",
                            Role = 20,
                            Senha = "B5D3A85785B854548A440F1EA52F19EF920AB9ED29136B977861B5E36983DEA2C92F29D5939A427AAAEDBC67C3B48A6CD9E1D45483D3796E0A60F113240BB49C"
                        },
                        new
                        {
                            Id = new Guid("293c8e29-466a-4acc-9170-dda5466986b5"),
                            Email = "renata.barros@gmail.com",
                            Matricula = "2300102",
                            Nome = "Renata Barros",
                            Role = 20,
                            Senha = "B5D3A85785B854548A440F1EA52F19EF920AB9ED29136B977861B5E36983DEA2C92F29D5939A427AAAEDBC67C3B48A6CD9E1D45483D3796E0A60F113240BB49C"
                        },
                        new
                        {
                            Id = new Guid("75e728fa-24ab-400f-99e6-720f187170d3"),
                            Email = "felipe.okagawa@gmail.com",
                            Matricula = "2400103",
                            Nome = "Felipe Okagawa",
                            Role = 20,
                            Senha = "B5D3A85785B854548A440F1EA52F19EF920AB9ED29136B977861B5E36983DEA2C92F29D5939A427AAAEDBC67C3B48A6CD9E1D45483D3796E0A60F113240BB49C"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
